# Generated by Django 5.2.12 on 2026-03-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoopToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whoop_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhoopSleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('duration_hours', models.FloatField()),
                ('awake_pct', models.FloatField(default=0)),
                ('light_pct', models.FloatField(default=0)),
                ('deep_pct', models.FloatField(default=0)),
                ('recovery_score', models.IntegerField(default=0)),
                ('hrv', models.FloatField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date'],
                'unique_together': {('user', 'recorded_date')},
            },
        ),
    ]
